apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: otel-demo
  name: helm-manager
rules:
# Helm stores release info here
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Typical resources created by the opentelemetry-demo chart
- apiGroups: [""]
  resources: ["services", "pods", "serviceaccounts", "persistentvolumeclaims"]
  verbs: ["*"]
- apiGroups: ["apps","batch","autoscaling","policy"]
  resources: ["deployments","statefulsets","daemonsets","replicasets",
              "jobs","cronjobs","poddisruptionbudgets"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: otel-demo
  name: helm-manager-binding
subjects:
- kind: ServiceAccount
  name: jenkins-helm
  namespace: cicd
roleRef:
  kind: Role
  name: helm-manager
  apiGroup: rbac.authorization.k8s.io
